### ISSUE TITLE
How to create data layer variables?

### ISSUE THREAD

**Issue by rmuktader** [dmvass/universal-analytics-python3#2]
Is the following a proper way to send additional variable values with events?

    tracker.send(
        'event',
        'Adoption',
        'potentialUsers & neverSignedIn',
        'counts for potentialUsers & neverSignedIn',
        {
            'noninteraction': 1,
            'totalActiveUsers': total_active_users,
            'totalUsersNeverSignedIn': total_users_never_signed_in
        }
    )

Many thanks in advance for any assistance you provide.

**Comment by dmvass** [comment]
@rmuktader yes, it's a recommended way to send additional variables to avoid camel case for python variable naming.

Please see some examples of usage from tests:
https://github.com/dmvass/universal-analytics-python3/blob/master/tests/test_tracker.py#L92
https://github.com/dmvass/universal-analytics-python3/blob/master/tests/test_tracker.py#L111
