### ISSUE TITLE
Setting 'exp' for Google Optimize server-side experiments does not work

### ISSUE THREAD

**Issue by nbeuchat** [dmvass/universal-analytics-python3#4]
**Describe the bug**
When creating server-side experiment on Google Optimize (which uses Google Analytics to track the results), we need to set the `exp` dimension and send a hit (see: https://developers.google.com/optimize/devguides/experiments#add-ga-tracking-code-to-variations). With the current implementation, the `exp` parameter is not sent to Google Analytics. 

**To Reproduce**

- Create an experiment in Google Optimize with two variants and get the experiment id
- In a script, run:
```
experiment_value = f"{experiment_id}.{variant_id}
ga_tracker = Tracker(UA_TRACKING_ID, http, user_id=user_id, client_id=user_id)
ga_tracker.set("exp", experiment_value)
ga_tracker.send("event", "Experiment", experiment_value)
```
- In Google Analytics, the event is visible with the correct value but the `Experiment ID` and `Variant ID` dimensions are not

Putting a debug point in the `send` method shows that the `exp` is not part of the `data` sent to Google Analytics. 

**Expected behavior**
The `exp` should be part of the data sent to Google Analytics

**Additional context**
N/A

**Comment by nbeuchat** [comment]
Note that if I do: `ga_tracker.alias(safe_unicode, "exp", "experiment")`, it works fine.

**Comment by dmvass** [comment]
@nbeuchat thanks for report! Will check it as soon as possible.
